- name: Demo on load another file
  hosts: all
  become: yes
  tasks: 
   - name: Print Hello World
     ansible.builtin.debug:
      msg: "Hello, World!"

   - name: Include another file
     ansible.builtin.include_tasks: 
       file: another.yml
    